model:
  model_code: <model_code>
  model_name: <model_name>
  experiment_name: <model_code>_<dataset_name>
  pretrained: true # If available, use pretrained weights
  load_checkpoint: false # If true, load the checkpoint specified below
  checkpoint_path: ''
  freeze_params: true
  encoder_dim: 2048
  decoder_channels: 2048
  n_way: 5        # Number of classes per episode
  k_shot: 5       # Number of support examples per class
  q_queries: 6    # Number of query examples per class
  k_queries: 128 # For few-shot learning, this will be the batch size
  hidden_dim: 512  # Hidden dimension for FSL encoder
  embedding_dim: 128  # Embedding dimension for FSL encoder

optimizer:
  name: adam
  lr: 1e-3
  weight_decay: 1e-4

loss:
  name: 0