model:
  model_code: <model_code>
  model_name: <model_name>
  freeze_params: true
  encoder_dim: 2048
  decoder_channels: 2048
  experiment_name: <model_code>_<dataset_name>
  pretrained: true # If available, use pretrained weights
  load_checkpoint: false # If true, load the checkpoint specified below
  checkpoint_path: ''


optimizer:
  name: adam
  lr: 1e-3
  weight_decay: 1e-4


loss:
  name: "cross_entropy" 