data:
  dataset_type: StandardImageDataset
  train_dir: datasets/final/bracs/train
  test_dir: datasets/final/bracs/test
  class_mapping: {ClassA: 0, ClassB: 1, ClassC: 2}
  batch_size: 64
  batch_size_test: 64
  num_workers: 3
  suffle_train: true
  suffle_test: false
  
transform:
  train:
    resize: [224, 224]
    horizontal_flip: true
    color_jitter:
      brightness: 0.4
      contrast: 0.4
      saturation: 0.4
      hue: 0.1
      probability: 0.4
      gaussian_noise:
        var_limit: [5.0, 30.0]
        mean: 0.0
        probability: 0.4
      gaussian_blur:
        blur_limit: [3, 7]
        probability: 0.4
    random_grayscale: 0.2
    normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
    to_tensor: true
  test:
    resize: [224, 224]
    normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
    to_tensor: true
