data:
  dataset_type: PrecomputedEmbeddingDataset
  train_npz_path: 
    ./local_experiments/<model_code>/ubc-ovarian-cancer/embeddings_train.npz
  test_npz_path: 
    ./local_experiments/<model_code>/ubc-ovarian-cancer/embeddings_test.npz
  batch_size_train: 32
  batch_size_eval: 64
  num_workers: 0
  shuffle_train: true
  shuffle_test: false
  shuffle_seed: 2025
  semantic_attributes: true
  class_mapping: {CC: 0, EC: 1, HGSC: 2, LGSC: 3, MC: 4}
transform:
  train: {to_tensor: true}
  test: {to_tensor: true}
model: 
  num_classes: 5
  encoder_dim: 133 # 128 + num_classes
