data:
  dataset_type: FewShotFolderDataset    # Specify the dataset type (e.g., terumo, etc.)
  train_dir: data/ubc-ovarian-cancer/train
  test_dir: data/ubc-ovarian-cancer/test-retrieval
  class_mapping: {CC: 0, EC: 1, HGSC: 2, LGSC: 3, MC: 4}
  batch_size_train: 1 # For few-shot learning, aways 1 
  batch_size_eval: 64
  num_workers: 1  # Number of workers to load the data
  shuffle_train: true  # Shuffle the training data
  shuffle_test: false # Shuffle the test data
  
  train_test_split: 0.2 # Split data into 80% training and 20% testing
  train_val_split: 0.1 # Use 10% of training data as validation
  shuffle_seed: 2025
  
  fixed_support_set: false
  semantic_attributes: true
model:
  num_classes: 5
  n_way: 5
  
transform:
  train:
    resize: [224, 224]
    horizontal_flip: true
    color_jitter:
      brightness: 0.4
      contrast: 0.4
      saturation: 0.4
      hue: 0.1
      probability: 0.4
      gaussian_noise:
        var_limit: [5.0, 30.0]
        mean: 0.0
        probability: 0.4
      gaussian_blur:
        blur_limit: [3, 7]
        probability: 0.4
    random_grayscale: 0.2
    normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
    to_tensor: true
  test:
    resize: [224, 224]
    normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
    to_tensor: true
