loss:
  name: mse
optimizer:
  name: adam
  lr: 1e-3
  weight_decay: 1e-4
training:
  pipeline: <pipeline_type>
  epochs: 1
  lr_scheduler:
    name: step_lr
    step_size: 10
  early_stopping_patience: 10
evaluation:
  enabled: true
  pipeline: default
  load_embeddings: false
  embeddings_path: ''
  save_embeddings: true
  normalize_embeddings: false
  list_of_metrics:
    - type: map@k
      k_values: [1, 3, 6, 9, 12, 15]
logging:
  log_file: ./logs.txt
  log_level: INFO
metric_logging:
  tool: txt
output:
  results_dir: ./local_experiments/<model_name>/<dataset_name>

# Example: pipeline_type can be 'train_few_shot_leaning', 'train_mynet', etc.

