training:
  pipeline: <pipeline_type>
  epochs: 2
  early_stopping_patience: 10
  val_retrieval:
    n_db_images: 100
    n_query_images: 5
    seed: 42

evaluation:
  enabled: true
  pipeline: retrieval_evaluator # Specify the evaluation pipeline. 'retrieval_evaluator' for standard image retrieval.
  load_embeddings: false # Load precomputed embeddings
  embeddings_path: '' # Path to load embeddings if needed
  save_embeddings: true
  normalize_embeddings: false
  list_of_metrics:
    - type: map@k
      k_values: [1, 3, 6, 9, 12, 15]
      similarity_type: similarity # similarity or distance
      similarity_fn: cosine # cosine, euclidean, custom

logging:
  log_file: ./logs.txt
  log_level: INFO

metric_logging:
  tool: txt # txt, mlflow

output:
  results_dir: ./local_experiments/<model_name>/<dataset_name>

