data:
  dataset_type: EmbeddingDataset
  data_path: ./local_experiments/uni_fsl/glomerulus/uni_fsl_glomerulus_2025-10-18_17-33-36/embeddings_2025-10-18_17-44-06.npz
  class_mapping: {Crescent: 0, Hypercelularidade: 1, Membranous: 2, Normal: 3, Podocitopatia: 4, Sclerosis: 5}
  batch_size_train: 32
  batch_size_eval: 64
  num_workers: 0  # Number of workers to load the data
  shuffle_train: true  # Shuffle the training data
  shuffle_test: false # Shuffle the test data

  train_test_split: 0.2 # Split data into 80% training and 20% testing
  train_val_split: 0.1 # Use 10% of training data as validation
  shuffle_seed: 2025
  
transform:
#  train:
#    resize: [224, 244]
#    to_tensor: true
#  test:
#    resize: [224, 224]
#    to_tensor: true
  train:
    resize: [224, 224]
    horizontal_flip: true
    color_jitter:
      brightness: 0.4
      contrast: 0.4
      saturation: 0.4
      hue: 0.1
      probability: 0.4
      gaussian_noise:
        var_limit: [5.0, 30.0]
        mean: 0.0
        probability: 0.4
      gaussian_blur:
        blur_limit: [3, 7]
        probability: 0.4
    random_grayscale: 0.2
    normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
    to_tensor: true
  test:
    resize: [224, 224]
    normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
    to_tensor: true

model:
  num_classes: 6
  model_code: 2_branch_mlp
  model_name: 2_branch_mlp
  experiment_name: 2_branch_mlp_uni_glomerulus
  embedding_model: uni 
  pretrained: true # If available, use pretrained weights
  load_checkpoint: false # If true, load the checkpoint specified below
  checkpoint_path: ''
  freeze_params: true
  encoder_dim: 2048
  decoder_channels: 128

  # N_BRANCH_MLP
  n_mlp_branches: 2
  mlp_layers: [512,128]
  mlp_activation: relu

optimizer:
  name: adam
  lr: 1e-3
  weight_decay: 1e-4

loss:
  name: supervised_contrastive_attention
  temperature: 0.7
  pairwise_similarity_fn: cosine_similarity

training:
  pipeline: terumo_trainer
  epochs: 2
  early_stopping_patience: 10
  val_retrieval:
    n_db_images: 100
    n_query_images: 5
    seed: 42

evaluation:
  enabled: true
  pipeline: retrieval_evaluator # Specify the evaluation pipeline. 'retrieval_evaluator' for standard image retrieval.
  load_embeddings: false # Load precomputed embeddings
  embeddings_path: '' # Path to load embeddings if needed
  save_embeddings: true
  normalize_embeddings: false
  list_of_metrics:
    - type: map@k
      k_values: [1, 3, 6, 9, 12, 15]
      similarity_type: similarity # similarity or distance
      similarity_fn: cosine # cosine, euclidean, custom

logging:
  log_file: ./logs.txt
  log_level: INFO

metric_logging:
  tool: txt # txt, mlflow

output:
  results_dir: ./local_experiments/2_branch_mlp/uni/glomerulus/

