data:
  dataset_type: StandardImageDataset
  dataset_dir: /datasets/terumo-data-jpeg/
  class_mapping: {Crescent: 0, Hypercelularidade: 1, Membranous: 2, Normal: 3, Podocitopatia: 4, Sclerosis: 5}
  batch_size_train: 64 
  batch_size_eval: 64
  num_workers: 3  # Number of workers to load the data
  shuffle_train: true  # Shuffle the training data
  shuffle_test: false # Shuffle the test data
  train_test_split: 0.2 # Split data into 80% training and 20% testing
  train_val_split: 0.1 # Use 10% of training data as validation
  shuffle_seed: 2025
  
model: {num_classes: 5, model_code: resnet, model_name: resnet18_classif, 
    freeze_params: true, encoder_dim: 2048, decoder_channels: 2048, 
    experiment_name: resnet_glomerulus, pretrained: true, load_checkpoint: 
    false, checkpoint_path: ''}
transform:
  train:
    resize: [224, 224]
    horizontal_flip: true
    color_jitter:
      brightness: 0.4
      contrast: 0.4
      saturation: 0.4
      hue: 0.1
      probability: 0.4
      gaussian_noise:
        var_limit: [5.0, 30.0]
        mean: 0.0
        probability: 0.4
      gaussian_blur:
        blur_limit: [3, 7]
        probability: 0.4
    random_grayscale: 0.2
    normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
    to_tensor: true
  test:
    resize: [224, 224]
    normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
    to_tensor: true
optimizer: {name: adam, lr: '1e-3', weight_decay: '1e-4'}
loss: {name: cross_entropy}
training:
  pipeline: default_trainer
  epochs: 2
  early_stopping_patience: 10
  val_retrieval: {n_db_images: 100, n_query_images: 5, seed: 42}
evaluation:
  enabled: true
  pipeline: retrieval_evaluator
  load_embeddings: false
  embeddings_path: ''
  save_embeddings: true
  normalize_embeddings: false
  list_of_metrics:
  - type: map@k
    k_values: [1, 3, 6, 9, 12, 15]
    similarity_type: similarity
    similarity_fn: cosine
logging: {log_file: ./logs.txt, log_level: INFO}
metric_logging: {tool: txt}
output: {results_dir: ./local_experiments/resnet18_classif/glomerulus}
